package templates

const (
	TS_ENTITY_TEMPLATE = `// This file was auto-generated by fabric. Delete this comment if the file is already checked and OK.
	export interface {{.Name | title}}Data {
		uid: string;
		{{range .Params}}{{.Name}}: {{.ParamType}}{{if .Optional}} | undefined{{end}};
		{{end}}
	}

	export class {{.Name | title}} {
		readonly uid: string;
		{{range .Params}}readonly {{.Name}}{{if .Optional}}?{{end}}: {{.ParamType}};
		{{end}}
		protected constructor(data: {{.Name | title}}Data) {
			this.uid = data.uid || crypto.randomUUID(),
			{{range .Params}}this.{{.Name}} = data.{{.Name}},
			{{end}}
		}

		static create(data: {{.Name | title}}Data): {{.Name | title}} {
			return new {{.Name | title}}(data);
		}

		static fromPlainObject(data: {{.Name | title}}Data): {{.Name | title}} {
			return new {{.Name | title}}(data)
		}

		toPlainObject(): {{.Name | title}}Data & { uid: string } {
			return {
				uid: this.uid,
				{{range .Params}}{{.Name}}: this.{{.Name}},
				{{end}}
			};
		}

		update(changes: Partial<{{.Name | title}}Data>): {{.Name | title}} {
			return {{.Name | title}}.create({
	      uid: this.uid,
				{{range .Params}}{{.Name}}: changes.{{.Name}} ?? this.{{.Name}},
				{{end}}
	    })
	  }
	}
	`
)
