package templates

const (
	TS_ENTITY_TEMPLATE = `// This file was auto-generated by fabric. Delete this comment if the file is already checked and OK.
	export interface I{{.Name | title}}Map {
		uid: string;
		{{range .Params}}{{.Name}}: {{.ParamType}}{{if .Optional}} | undefined{{end}};{{end}}
	}

	export abstract class I{{.Name | title}} {
		protected _uid: string;
		{{range .Params}}protected _{{.Name}}: {{.ParamType}}{{if .Optional}} | undefined{{end}};{{end}}
		abstract toPlainObject(): I{{.Name | title}}Map;
		abstract get uid(): string;
		{{range .Params}}abstract get {{.Name}}(): {{.ParamType}}{{if .Optional}} | undefined{{end}};{{end}}
	}

	export class {{.Name | title}} extends I{{.Name | title}} {
		protected readonly _uid: string;
		{{range .Params}}protected readonly _{{.Name}}: {{.ParamType}}{{if .Optional}} | undefined{{end}};{{end}}
		protected constructor(data: I{{.Name | title}}Map) {
			super();
			this._uid = data.uid || crypto.randomUUID();
			{{range .Params}}this._{{.Name}} = data.{{.Name}}{{if not .Optional}};{{else}} ?? undefined;{{end}}{{end}}
		}

		static create(data: I{{.Name | title}}Map): I{{.Name | title}} {
			return new {{.Name | title}}(data);
		}

		get uid(): string {
			return this._uid;
		}

		{{range .Params}}get {{.Name}}(): {{.ParamType}}{{if .Optional}} | undefined{{end}} { return this._{{.Name}}; }{{end}} 

		toPlainObject(): I{{.Name | title}}Map {
			return {
				"uid": this._uid,
				{{range .Params}}"{{.Name}}": this._{{.Name}}{{if not .Optional}},{{end}}{{end}}
			}
		}
	}
	`
)
